url: "taahachaudhry.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/taaha" # the subpath of your site, e.g. /blog
title: "Taaha Chaudhry" # the name of your site, e.g. ACME Corp.
email: "tbchaudhry@ucdavis.edu"
version: 3.0.0

usernames: {
  github:  "taahachaudhry",
  linkedin: "taahachaudhry"
}

production_url : http://taahachaudhry.github.io/
BASE_PATH : http://taahachaudhry.github.io/
